In [2]:
import os
# Find the latest version of spark 3.2 from http://www.apache.org/dist/spark/ and enter as the spark version
# For example:
# spark_version = 'spark-3.2.3'
spark_version = 'spark-3.2.3'
os.environ['SPARK_VERSION']=spark_version

# Install Spark and Java
!apt-get update
!apt-get install openjdk-11-jdk-headless -qq > /dev/null
!wget -q http://archive.apache.org/dist/spark/$SPARK_VERSION/$SPARK_VERSION-bin-hadoop2.7.tgz
!tar xf $SPARK_VERSION-bin-hadoop2.7.tgz
!pip install -q findspark

# Set Environment Variables
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64"
os.environ["SPARK_HOME"] = f"/content/{spark_version}-bin-hadoop2.7"

# Start a SparkSession
import findspark
findspark.init()

Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Get:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease [1,581 B]
Get:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:4 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:5 https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/ InRelease [3,622 B]
Get:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Hit:7 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu focal InRelease
Hit:8 http://ppa.launchpad.net/cran/libgit2/ubuntu focal InRelease
Get:9 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages [975 kB]
Hit:10 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal InRelease
Hit:11 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu focal InRelease
Get:12 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [1,029 kB]
Hit:13 http://ppa.launchpad.net/ubuntugis/ppa/ubuntu focal 

In [3]:
# Download the Postgres driver that will allow Spark to interact with Postgres.
!wget https://jdbc.postgresql.org/download/postgresql-42.2.16.jar

--2023-04-17 21:57:15--  https://jdbc.postgresql.org/download/postgresql-42.2.16.jar
Resolving jdbc.postgresql.org (jdbc.postgresql.org)... 72.32.157.228, 2001:4800:3e1:1::228
Connecting to jdbc.postgresql.org (jdbc.postgresql.org)|72.32.157.228|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1002883 (979K) [application/java-archive]
Saving to: ‘postgresql-42.2.16.jar’

postgresql-42.2.16. 100%[===================>] 979.38K  --.-KB/s    in 0.1s    

2023-04-17 21:57:15 (9.23 MB/s) - ‘postgresql-42.2.16.jar’ saved [1002883/1002883]



In [4]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("Final-Project").config("spark.driver.extraClassPath","/content/postgresql-42.2.16.jar").getOrCreate()

### Load Amazon Data into Spark DataFrame

In [5]:
from pyspark import SparkFiles
# Load in the review data from S3 into the dataframe
url = "https://unbearable-1-project-bucket.s3.us-east-2.amazonaws.com/Diabetes_Key_Indicators.csv"
spark.sparkContext.addFile(url)
df = spark.read.option("encoding", "UTF-8").csv(SparkFiles.get(""), sep=",", header=True, inferSchema=True)
df.show()

+---+------+------+-----------+------+-----+-------+--------+-------------+-------------+--------+--------+--------+--------+--------+-------+-------+--------+-------+--------------------+--------+--------+--------+--------+--------+-------+-------+--------+--------+-------+--------+-------+------+-------+--------+--------+--------+--------+--------+--------+--------+--------+-------+------+--------+-------+--------+--------+--------+--------+-------+-------+--------+--------+--------+--------+--------+--------+--------+--------+--------+-------+--------+--------+--------+-------+-----+--------+--------+--------+--------+--------+-------+--------+-------+--------+-------+-------+----+-----+------+--------+--------+--------+--------+--------+-------+--------+-------+--------+--------+--------+--------+--------+--------+--------+-------+--------+------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+-------+--------+-------+----

In [6]:
new_df = df.select(["DIABETE4",
                    "_RACE",
                    "TOLDHI3",
                    "BPHIGH6",
                    "_BMI5",
                    "SMOKE100",
                    "_RFBING5",
                    "EDUCA",
                    "GENHLTH",
                    "_AGEG5YR",
                    "EXERANY2",
                    "FRUIT2",
                    "VEGETAB2",
                    "_INCOMG1",
                    "MEDCOST1",
                    "_SEX"])
new_df.show()

+--------+-----+-------+-------+------+--------+--------+-----+-------+--------+--------+------+--------+--------+--------+----+
|DIABETE4|_RACE|TOLDHI3|BPHIGH6| _BMI5|SMOKE100|_RFBING5|EDUCA|GENHLTH|_AGEG5YR|EXERANY2|FRUIT2|VEGETAB2|_INCOMG1|MEDCOST1|_SEX|
+--------+-----+-------+-------+------+--------+--------+-----+-------+--------+--------+------+--------+--------+--------+----+
|     3.0|  1.0|    1.0|    3.0|1454.0|     1.0|     1.0|  4.0|    5.0|    11.0|     2.0| 101.0|   101.0|     3.0|     2.0| 2.0|
|     1.0|  2.0|    1.0|    1.0|  null|     2.0|     1.0|  6.0|    3.0|    10.0|     1.0| 101.0|   207.0|     9.0|     2.0| 2.0|
|     1.0|  2.0|    2.0|    1.0|2829.0|     2.0|     1.0|  4.0|    2.0|    11.0|     2.0| 101.0|   203.0|     2.0|     2.0| 2.0|
|     1.0|  1.0|    1.0|    1.0|3347.0|     2.0|     2.0|  4.0|    2.0|     9.0|     1.0| 203.0|   205.0|     5.0|     2.0| 2.0|
|     1.0|  7.0|    1.0|    4.0|2873.0|     2.0|     1.0|  3.0|    5.0|    12.0|     1.0| 101.0| 

### Clean up Columns

In [7]:
import pandas as pd
pandas_df = new_df.toPandas()
pandas_df = pandas_df.dropna()

pandas_df

DIABETE4  _RACE  TOLDHI3  BPHIGH6   _BMI5  SMOKE100  _RFBING5  EDUCA  \
0            3.0    1.0      1.0      3.0  1454.0       1.0       1.0    4.0   
2            1.0    2.0      2.0      1.0  2829.0       2.0       1.0    4.0   
3            1.0    1.0      1.0      1.0  3347.0       2.0       2.0    4.0   
4            1.0    7.0      1.0      4.0  2873.0       2.0       1.0    3.0   
5            3.0    1.0      2.0      3.0  2437.0       1.0       1.0    5.0   
...          ...    ...      ...      ...     ...       ...       ...    ...   
438687       1.0    8.0      1.0      1.0  2148.0       2.0       2.0    2.0   
438688       2.0    9.0      2.0      1.0  2469.0       1.0       1.0    4.0   
438690       3.0    2.0      1.0      3.0  3068.0       2.0       1.0    6.0   
438691       3.0    9.0      2.0      1.0  2373.0       2.0       1.0    4.0   
438692       3.0    2.0      1.0      3.0  3171.0       2.0       1.0    6.0   

        GENHLTH  _AGEG5YR  EXERANY2  FRUIT2  VEGETAB2  _INCOMG1  MEDCOST1  \
0           5.0      11.0       2.0   101.0     101.0       3.0       2.0   
2           2.0      11.0       2.0   101.0     203.0       2.0       2.0   
3           2.0       9.0       1.0   203.0     205.0       5.0       2.0   
4           5.0      12.0       1.0   101.0     101.0       2.0       2.0   
5           3.0      13.0       2.0   202.0     201.0       4.0       2.0   
...         ...       ...       ...     ...       ...       ...       ...   
438687      4.0      10.0       1.0   315.0     205.0       2.0       2.0   
438688      2.0       3.0       1.0   210.0     103.0       3.0       1.0   
438690      2.0       7.0       1.0   102.0     101.0       6.0       2.0   
438691      2.0      10.0       1.0   101.0     101.0       4.0       2.0   
438692      1.0       6.0       1.0   305.0     305.0       4.0       2.0   

        _SEX  
0        2.0  
2        2.0  
3        2.0  
4        1.0  
5        1.0  
...      ...  
438687   1.0  
438688   2.0  
438690   1.0  
438691   1.0  
438692   2.0  

[319363 rows x 16 columns]

In [8]:
# check for unique values to replace for encoding
pandas_df.EDUCA.unique()

array([4., 3., 5., 6., 2., 9., 1.])

In [9]:
# Replace Values based on responses provided in survey response form and confirm updated values
pandas_df = pandas_df.replace({"EDUCA":{4.:"High School Grad",
                                        6.:"College Grad",
                                        3.:"Some High School",
                                        5.:"Some College",
                                        2.:"Elementary",
                                        1.:"None",
                                        9.:""}})
pandas_df.EDUCA.unique()


array(['High School Grad', 'Some High School', 'Some College',
       'College Grad', 'Elementary', '', 'None'], dtype=object)

In [10]:
pandas_df.GENHLTH.unique()

array([5., 2., 3., 4., 1., 7., 9.])

In [11]:
# Replace Values based on responses provided in survey response form and confirm confirm updated values
pandas_df = pandas_df.replace({"GENHLTH":{1.:"Excellent",
                                          2.:"Very Good",
                                          3.:"Good",
                                          4.:"Fair",
                                          5.:"Poor",
                                          7.:"",
                                          9.:""}})
pandas_df.GENHLTH.unique()

array(['Poor', 'Very Good', 'Good', 'Fair', 'Excellent', ''], dtype=object)

In [12]:
pandas_df._INCOMG1.unique()

array([3., 2., 5., 4., 9., 1., 6., 7.])

In [13]:
# Replace Values based on responses provided in survey response form and confirm confirm updated values
pandas_df = pandas_df.replace({"_INCOMG1":{1.:"Less than $15,000",
                                           2.:"$15,000 to < $25,000",
                                           3.:"$25,000 to < $35,000",
                                           4.:"$35,000 to < $50,000",
                                           5.:"$50,000 to < $100,000",
                                           6.:"$100,000 to < $200,000",
                                           7.:" > $200,000",
                                           9.:""}})
pandas_df._INCOMG1.unique()

array(['$25,000 to < $35,000', '$15,000 to < $25,000',
       '$50,000 to < $100,000', '$35,000 to < $50,000', '',
       'Less than $15,000', '$100,000 to < $200,000', ' > $200,000'],
      dtype=object)

In [14]:
# Check unique values for Race
pandas_df._RACE.unique()

array([1., 2., 7., 9., 8., 3., 4., 6., 5.])

In [15]:
# Replace values based on responses in survey for Race
pandas_df = pandas_df.replace({"_RACE":{1.:"White",
                               2.:"Black",
                               3.:"American Indian or Alaskan Native",
                               4.:"Asian",
                               5.:" Native Hawaiian or other Pacific Islander",
                               6.:"Other",
                               7.:"Multiracial",
                               8.:"Hispanic",
                               9.:""}})
pandas_df._RACE.unique()

array(['White', 'Black', 'Multiracial', '', 'Hispanic',
       'American Indian or Alaskan Native', 'Asian', 'Other',
       ' Native Hawaiian or other Pacific Islander'], dtype=object)

In [16]:
# Check unique values for TOLDHI3 (high cholesterol)
pandas_df.TOLDHI3.unique()

array([1., 2., 7., 9.])

In [17]:
# Replace values based on responses in survey for cholesterol
pandas_df = pandas_df.replace({"TOLDHI3":{1.:"Yes",
                                          2.:"No",
                                          7.:"",
                                          9.:""}})
pandas_df.TOLDHI3.unique()

array(['Yes', 'No', ''], dtype=object)

In [18]:
# BMI Decimal Change
pandas_df['_BMI5'] = pandas_df['_BMI5'] / 100.0
pandas_df['_BMI5'] = round(pandas_df['_BMI5'], 2)

In [19]:
# Check unique values for SMOKE100 
pandas_df.SMOKE100.unique()

array([1., 2., 7., 9.])

In [20]:
# Replace values based on responses in survey for SMOKE100
pandas_df = pandas_df.replace({"SMOKE100":{1.:"Yes",
                                           2.:"No",
                                           7.:"",
                                           9.:""}})
pandas_df.SMOKE100.unique()

array(['Yes', 'No', ''], dtype=object)

In [21]:
# Check unique values for _RFBING5
pandas_df._RFBING5.unique()

array([1., 2., 9.])

In [22]:
# Replace values based on responses in survey for _RFBING5
pandas_df = pandas_df.replace({"_RFBING5":{1.:"Yes",
                                           2.:"No",
                                           9.:""}})
pandas_df._RFBING5.unique()

array(['Yes', 'No', ''], dtype=object)

In [23]:
# Check unique values for EXERANY2
pandas_df.EXERANY2.unique()

array([2., 1., 7., 9.])

In [24]:
# Replace values based on responses in survey for EXERANY2
pandas_df = pandas_df.replace({"EXERANY2":{1.:"Yes",
                                           2.:"No",
                                           7.:"",
                                           9.:""}})
pandas_df.EXERANY2.unique()

array(['No', 'Yes', ''], dtype=object)

In [25]:
# Check unique values for DIABETE4
pandas_df.DIABETE4.unique()

array([3., 1., 4., 2., 7., 9.])

In [26]:
# Replace values based on responses for DIABETE4
pandas_df = pandas_df.replace({"DIABETE4":{1.: "Yes", 
                                           2.: "Yes", 
                                           3.: "No",
                                           4.: "No", 
                                           7.: "", 
                                           9.:""}})


In [27]:
# Check unique values for FRUIT2
pandas_df.FRUIT2.unique()

array([101., 203., 202., 312., 204., 205., 302., 102., 301., 330., 555.,
       307., 300., 201., 305., 303., 306., 103., 777., 207., 308., 220.,
       206., 315., 310., 105., 304., 235., 320., 325., 314., 104., 106.,
       208., 107., 316., 309., 317., 390., 360., 999., 345., 210., 340.,
       221., 215., 110., 130., 399., 230., 199., 299., 335., 324., 214.,
       212., 328., 125., 327., 114., 336., 250., 218., 108., 209., 326.,
       350., 323., 318., 321., 342., 322., 115., 120., 109., 118., 123.,
       180., 216., 160., 150., 311., 113., 380., 192., 225., 228., 329.,
       332., 370., 240., 122., 294., 211., 112., 339., 375., 331., 392.,
       363., 127., 111., 333., 121., 384., 226., 131., 313., 241., 134.,
       344., 222., 116., 365., 355., 224., 338., 232., 397., 124., 227.,
       319., 188., 213., 223., 334., 293., 190., 193., 166., 398., 337.,
       217., 260., 396., 119., 117., 198., 341., 275., 261., 128., 191.,
       348., 139., 298., 255., 133., 189., 140., 17

In [28]:
import numpy as np
pandas_df = pandas_df.replace({"FRUIT2":{300.:500.}})
pandas_df['FRUIT2'] = np.where(pandas_df['FRUIT2'].between(0,400), "Yes", pandas_df['FRUIT2'])
pandas_df = pandas_df.replace({"FRUIT2":{'500.0': "No", '555.0': "No", '777.0': "", '999.0': ""}})
pandas_df.FRUIT2.unique()

array(['Yes', 'No', ''], dtype=object)

In [29]:
# Check unique values for VEGETEB2
pandas_df.VEGETAB2.unique()

array([101., 203., 205., 201., 202., 204., 303., 207., 330., 306., 102.,
       105., 555., 777., 307., 301., 310., 320., 315., 225., 329., 104.,
       304., 302., 206., 103., 214., 325., 312., 316., 300., 210., 308.,
       328., 305., 314., 360., 209., 107., 327., 212., 333., 318., 324.,
       365., 326., 317., 340., 999., 311., 309., 323., 220., 321., 106.,
       313., 215., 199., 345., 128., 399., 355., 130., 350., 125., 115.,
       356., 223., 114., 112., 332., 208., 331., 109., 322., 335., 250.,
       299., 375., 150., 390., 119., 230., 108., 120., 111., 110., 160.,
       240., 175., 354., 319., 218., 348., 191., 370., 233., 217., 228.,
       221., 127., 245., 129., 380., 165., 211., 260., 124., 123., 339.,
       140., 338., 222., 227., 121., 292., 336., 192., 280., 295., 213.,
       359., 226., 358., 216., 362., 342., 393., 134., 189., 133., 382.,
       122., 231., 166., 275., 116., 139., 131., 352., 294., 180., 117.,
       177., 395., 269., 296., 171., 118., 337., 35

In [30]:
#VEGETEB2!!!! This needs to be updated - see above for values
pandas_df = pandas_df.replace({"VEGETAB2":{300.:500.}})
pandas_df['VEGETAB2'] = np.where(pandas_df['VEGETAB2'].between(0,400), "Yes", pandas_df['VEGETAB2'])
pandas_df = pandas_df.replace({"VEGETAB2":{'500.0': "No", '555.0': "No", '777.0': "", '999.0': ""}})
pandas_df.VEGETAB2.unique()

array(['Yes', 'No', ''], dtype=object)

In [31]:
# Check unique values for MEDCOST1
pandas_df.MEDCOST1.unique()

array([2., 1., 7., 9.])

In [32]:
#MEDCOST1	updates with survey results
pandas_df = pandas_df.replace({"MEDCOST1":{1.:"Yes", 2.:"No", 7.:"", 9.:""}})
pandas_df.MEDCOST1.unique()

array(['No', 'Yes', ''], dtype=object)

In [33]:
# Check unique values for _SEX
pandas_df._SEX.unique()

array([2., 1.])

In [34]:
#_SEX
pandas_df = pandas_df.replace({"_SEX":{1.:"Male", 2.:"Female"}})

In [35]:
# Check unique values for BPHIGH6
pandas_df.BPHIGH6.unique()

array([3., 1., 4., 2., 7., 9.])

In [36]:
# Replace values based on responses for BPHIGH6
pandas_df = pandas_df.replace({"BPHIGH6": {1.: "Yes",
                                           2.: "Yes",
                                           3.: "No",
                                           4.: "No", 
                                           7.: "", 
                                           9.:""}})

In [37]:
pandas_df

DIABETE4        _RACE TOLDHI3 BPHIGH6  _BMI5 SMOKE100 _RFBING5  \
0            No        White     Yes      No  14.54      Yes      Yes   
2           Yes        Black      No     Yes  28.29       No      Yes   
3           Yes        White     Yes     Yes  33.47       No       No   
4           Yes  Multiracial     Yes      No  28.73       No      Yes   
5            No        White      No      No  24.37      Yes      Yes   
...         ...          ...     ...     ...    ...      ...      ...   
438687      Yes     Hispanic     Yes     Yes  21.48       No       No   
438688      Yes                   No     Yes  24.69      Yes      Yes   
438690       No        Black     Yes      No  30.68       No      Yes   
438691       No                   No     Yes  23.73       No      Yes   
438692       No        Black     Yes      No  31.71       No      Yes   

                   EDUCA    GENHLTH  _AGEG5YR EXERANY2 FRUIT2 VEGETAB2  \
0       High School Grad       Poor      11.0       No    Yes      Yes   
2       High School Grad  Very Good      11.0       No    Yes      Yes   
3       High School Grad  Very Good       9.0      Yes    Yes      Yes   
4       Some High School       Poor      12.0      Yes    Yes      Yes   
5           Some College       Good      13.0       No    Yes      Yes   
...                  ...        ...       ...      ...    ...      ...   
438687        Elementary       Fair      10.0      Yes    Yes      Yes   
438688  High School Grad  Very Good       3.0      Yes    Yes      Yes   
438690      College Grad  Very Good       7.0      Yes    Yes      Yes   
438691  High School Grad  Very Good      10.0      Yes    Yes      Yes   
438692      College Grad  Excellent       6.0      Yes    Yes      Yes   

                      _INCOMG1 MEDCOST1    _SEX  
0         $25,000 to < $35,000       No  Female  
2         $15,000 to < $25,000       No  Female  
3        $50,000 to < $100,000       No  Female  
4         $15,000 to < $25,000       No    Male  
5         $35,000 to < $50,000       No    Male  
...                        ...      ...     ...  
438687    $15,000 to < $25,000       No    Male  
438688    $25,000 to < $35,000      Yes  Female  
438690  $100,000 to < $200,000       No    Male  
438691    $35,000 to < $50,000       No    Male  
438692    $35,000 to < $50,000       No  Female  

[319363 rows x 16 columns]

In [38]:
pandas_df = pandas_df.replace({"_AGEG5YR": {1.: "Age 18 to 24",
                                            2.: "Age 25 to 29 ",
                                            3.: "Age 30 to 34 ",
                                            4.: "Age 35 to 39 ",
                                            5.: "Age 40 to 44",
                                            6.: "Age 45 to 49",
                                            7.: "Age 50 to 54",
                                            8.: "Age 55 to 59 ",
                                            9.: "Age 60 to 64 ",
                                            10.: "Age 65 to 69 ",
                                            11.: "Age 70 to 74 ",
                                            12.: "Age 75 to 79",
                                            13.: "Age 80 or older",
                                            14.: ""}})

In [39]:
pandas_df=pandas_df.mask(pandas_df == "")

In [40]:
pandas_df.isna().sum()

DIABETE4      402
_RACE        5867
TOLDHI3      2425
BPHIGH6       842
_BMI5           0
SMOKE100     1814
_RFBING5     5305
EDUCA         689
GENHLTH       611
_AGEG5YR     3690
EXERANY2      477
FRUIT2       5299
VEGETAB2     4572
_INCOMG1    51064
MEDCOST1      660
_SEX            0
dtype: int64

In [41]:
pandas_df = pandas_df.dropna()

In [42]:
pandas_df.reset_index(drop=True)

DIABETE4        _RACE TOLDHI3 BPHIGH6  _BMI5 SMOKE100 _RFBING5  \
0            No        White     Yes      No  14.54      Yes      Yes   
1           Yes        Black      No     Yes  28.29       No      Yes   
2           Yes        White     Yes     Yes  33.47       No       No   
3           Yes  Multiracial     Yes      No  28.73       No      Yes   
4            No        White      No      No  24.37      Yes      Yes   
...         ...          ...     ...     ...    ...      ...      ...   
250523       No        Black     Yes     Yes  20.98       No      Yes   
250524       No        Black      No      No  29.05       No      Yes   
250525      Yes     Hispanic     Yes     Yes  21.48       No       No   
250526       No        Black     Yes      No  30.68       No      Yes   
250527       No        Black     Yes      No  31.71       No      Yes   

                   EDUCA    GENHLTH         _AGEG5YR EXERANY2 FRUIT2 VEGETAB2  \
0       High School Grad       Poor    Age 70 to 74        No    Yes      Yes   
1       High School Grad  Very Good    Age 70 to 74        No    Yes      Yes   
2       High School Grad  Very Good    Age 60 to 64       Yes    Yes      Yes   
3       Some High School       Poor     Age 75 to 79      Yes    Yes      Yes   
4           Some College       Good  Age 80 or older       No    Yes      Yes   
...                  ...        ...              ...      ...    ...      ...   
250523  High School Grad       Good    Age 55 to 59       Yes    Yes      Yes   
250524      College Grad  Very Good    Age 25 to 29       Yes    Yes      Yes   
250525        Elementary       Fair    Age 65 to 69       Yes    Yes      Yes   
250526      College Grad  Very Good     Age 50 to 54      Yes    Yes      Yes   
250527      College Grad  Excellent     Age 45 to 49      Yes    Yes      Yes   

                      _INCOMG1 MEDCOST1    _SEX  
0         $25,000 to < $35,000       No  Female  
1         $15,000 to < $25,000       No  Female  
2        $50,000 to < $100,000       No  Female  
3         $15,000 to < $25,000       No    Male  
4         $35,000 to < $50,000       No    Male  
...                        ...      ...     ...  
250523    $25,000 to < $35,000       No    Male  
250524              > $200,000       No    Male  
250525    $15,000 to < $25,000       No    Male  
250526  $100,000 to < $200,000       No    Male  
250527    $35,000 to < $50,000       No  Female  

[250528 rows x 16 columns]

In [43]:
# Identify outliers in BMI data, create summary statistics to identify quartiles
# urban_drivers = urban_cities_df['driver_count']
bmi_df = pandas_df["_BMI5"]
bmi_df

0         14.54
2         28.29
3         33.47
4         28.73
5         24.37
          ...  
438685    20.98
438686    29.05
438687    21.48
438690    30.68
438692    31.71
Name: _BMI5, Length: 250528, dtype: float64

In [44]:
#get summary statistics
bmi_df.describe()

count    250528.000000
mean         28.978447
std           6.574445
min          12.020000
25%          24.410000
50%          27.890000
75%          32.190000
max          99.330000
Name: _BMI5, dtype: float64

In [45]:
bmi_q1 = bmi_df.quantile(0.25)
bmi_q3 = bmi_df.quantile(0.75)
bmi_iqr = bmi_q3 - bmi_q1

In [46]:
filtered_bmi_df = pandas_df.loc[(pandas_df["_BMI5"] > (bmi_q1 - (1.5 * bmi_iqr))) & (pandas_df["_BMI5"] < (bmi_q3 + (1.5 * bmi_iqr)))]
filtered_bmi_df

DIABETE4        _RACE TOLDHI3 BPHIGH6  _BMI5 SMOKE100 _RFBING5  \
0            No        White     Yes      No  14.54      Yes      Yes   
2           Yes        Black      No     Yes  28.29       No      Yes   
3           Yes        White     Yes     Yes  33.47       No       No   
4           Yes  Multiracial     Yes      No  28.73       No      Yes   
5            No        White      No      No  24.37      Yes      Yes   
...         ...          ...     ...     ...    ...      ...      ...   
438685       No        Black     Yes     Yes  20.98       No      Yes   
438686       No        Black      No      No  29.05       No      Yes   
438687      Yes     Hispanic     Yes     Yes  21.48       No       No   
438690       No        Black     Yes      No  30.68       No      Yes   
438692       No        Black     Yes      No  31.71       No      Yes   

                   EDUCA    GENHLTH         _AGEG5YR EXERANY2 FRUIT2 VEGETAB2  \
0       High School Grad       Poor    Age 70 to 74        No    Yes      Yes   
2       High School Grad  Very Good    Age 70 to 74        No    Yes      Yes   
3       High School Grad  Very Good    Age 60 to 64       Yes    Yes      Yes   
4       Some High School       Poor     Age 75 to 79      Yes    Yes      Yes   
5           Some College       Good  Age 80 or older       No    Yes      Yes   
...                  ...        ...              ...      ...    ...      ...   
438685  High School Grad       Good    Age 55 to 59       Yes    Yes      Yes   
438686      College Grad  Very Good    Age 25 to 29       Yes    Yes      Yes   
438687        Elementary       Fair    Age 65 to 69       Yes    Yes      Yes   
438690      College Grad  Very Good     Age 50 to 54      Yes    Yes      Yes   
438692      College Grad  Excellent     Age 45 to 49      Yes    Yes      Yes   

                      _INCOMG1 MEDCOST1    _SEX  
0         $25,000 to < $35,000       No  Female  
2         $15,000 to < $25,000       No  Female  
3        $50,000 to < $100,000       No  Female  
4         $15,000 to < $25,000       No    Male  
5         $35,000 to < $50,000       No    Male  
...                        ...      ...     ...  
438685    $25,000 to < $35,000       No    Male  
438686              > $200,000       No    Male  
438687    $15,000 to < $25,000       No    Male  
438690  $100,000 to < $200,000       No    Male  
438692    $35,000 to < $50,000       No  Female  

[242802 rows x 16 columns]

In [47]:
filtered_bmi_df.rename(columns={"DIABETE4": "Diabetes Status", 
                                "_RACE": "Ethnicity", 
                                "TOLDHI3": "High Cholesterol", 
                                "BPHIGH6": "High Blood Pressure",
                                "_BMI5": "BMI", 
                                "SMOKE100": "Smoked 100+ Cigarettes",
                                "_RFBING5": "Alcohol Use/Last 30 Days, 5+ Drinks",
                                "EDUCA": "Education", 
                                "GENHLTH": "General Health",
                                "_AGEG5YR": "Age Group",
                                "EXERANY2": "Exercise/Last 30 Days", 
                                "FRUIT2": "Fruit Consumption", 
                                "VEGETAB2": "Vegetable Consumption",
                                "_INCOMG1": "Income", 
                                "MEDCOST1": "Unable to See Doctor Due to Cost/Last Year",
                                "_SEX": "Gender"}, inplace=True)

<ipython-input-47-701c0f337eb4>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_bmi_df.rename(columns={"DIABETE4": "Diabetes Status",


In [48]:
filtered_bmi_df

Diabetes Status    Ethnicity High Cholesterol High Blood Pressure  \
0                   No        White              Yes                  No   
2                  Yes        Black               No                 Yes   
3                  Yes        White              Yes                 Yes   
4                  Yes  Multiracial              Yes                  No   
5                   No        White               No                  No   
...                ...          ...              ...                 ...   
438685              No        Black              Yes                 Yes   
438686              No        Black               No                  No   
438687             Yes     Hispanic              Yes                 Yes   
438690              No        Black              Yes                  No   
438692              No        Black              Yes                  No   

          BMI Smoked 100+ Cigarettes Alcohol Use/Last 30 Days, 5+ Drinks  \
0       14.54                    Yes                                 Yes   
2       28.29                     No                                 Yes   
3       33.47                     No                                  No   
4       28.73                     No                                 Yes   
5       24.37                    Yes                                 Yes   
...       ...                    ...                                 ...   
438685  20.98                     No                                 Yes   
438686  29.05                     No                                 Yes   
438687  21.48                     No                                  No   
438690  30.68                     No                                 Yes   
438692  31.71                     No                                 Yes   

               Education General Health        Age Group  \
0       High School Grad           Poor    Age 70 to 74    
2       High School Grad      Very Good    Age 70 to 74    
3       High School Grad      Very Good    Age 60 to 64    
4       Some High School           Poor     Age 75 to 79   
5           Some College           Good  Age 80 or older   
...                  ...            ...              ...   
438685  High School Grad           Good    Age 55 to 59    
438686      College Grad      Very Good    Age 25 to 29    
438687        Elementary           Fair    Age 65 to 69    
438690      College Grad      Very Good     Age 50 to 54   
438692      College Grad      Excellent     Age 45 to 49   

       Exercise/Last 30 Days Fruit Consumption Vegetable Consumption  \
0                         No               Yes                   Yes   
2                         No               Yes                   Yes   
3                        Yes               Yes                   Yes   
4                        Yes               Yes                   Yes   
5                         No               Yes                   Yes   
...                      ...               ...                   ...   
438685                   Yes               Yes                   Yes   
438686                   Yes               Yes                   Yes   
438687                   Yes               Yes                   Yes   
438690                   Yes               Yes                   Yes   
438692                   Yes               Yes                   Yes   

                        Income Unable to See Doctor Due to Cost/Last Year  \
0         $25,000 to < $35,000                                         No   
2         $15,000 to < $25,000                                         No   
3        $50,000 to < $100,000                                         No   
4         $15,000 to < $25,000                                         No   
5         $35,000 to < $50,000                                         No   
...                        ...                                        ...   
438685    $25,000 to < $35,000                          

In [49]:
# check summary statistics
filtered_bmi_df.describe()

BMI
count  242802.000000
mean       28.324162
std         5.420467
min        12.750000
25%        24.390000
50%        27.480000
75%        31.640000
max        43.850000

In [50]:
filtered_bmi_df.dtypes

Diabetes Status                                object
Ethnicity                                      object
High Cholesterol                               object
High Blood Pressure                            object
BMI                                           float64
Smoked 100+ Cigarettes                         object
Alcohol Use/Last 30 Days, 5+ Drinks            object
Education                                      object
General Health                                 object
Age Group                                      object
Exercise/Last 30 Days                          object
Fruit Consumption                              object
Vegetable Consumption                          object
Income                                         object
Unable to See Doctor Due to Cost/Last Year     object
Gender                                         object
dtype: object

In [56]:
# Create second dataframe
visualization_df = filtered_bmi_df.drop(['High Cholesterol', 'High Blood Pressure', 'Smoked 100+ Cigarettes', 'Alcohol Use/Last 30 Days, 5+ Drinks', 'Education', 'General Health', 'Exercise/Last 30 Days', 'Fruit Consumption', 'Vegetable Consumption', 'Unable to See Doctor Due to Cost/Last Year'], 1)


<ipython-input-56-94ca9221e93e>:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  visualization_df = filtered_bmi_df.drop(['High Cholesterol', 'High Blood Pressure', 'Smoked 100+ Cigarettes', 'Alcohol Use/Last 30 Days, 5+ Drinks', 'Education', 'General Health', 'Exercise/Last 30 Days', 'Fruit Consumption', 'Vegetable Consumption', 'Unable to See Doctor Due to Cost/Last Year'], 1)


In [61]:
visualization_df.dtypes

Diabetes Status     object
Ethnicity           object
BMI                float64
Age Group           object
Income              object
Gender              object
dtype: object

In [57]:
visualization_df.head()

Diabetes Status    Ethnicity    BMI        Age Group                 Income  \
0              No        White  14.54    Age 70 to 74    $25,000 to < $35,000   
2             Yes        Black  28.29    Age 70 to 74    $15,000 to < $25,000   
3             Yes        White  33.47    Age 60 to 64   $50,000 to < $100,000   
4             Yes  Multiracial  28.73     Age 75 to 79   $15,000 to < $25,000   
5              No        White  24.37  Age 80 or older   $35,000 to < $50,000   

   Gender  
0  Female  
2  Female  
3  Female  
4    Male  
5    Male

In [58]:
visualization_df.rename(columns={"DIABETE4": "Diabetes Status", "_RACE": "Ethnicity", "_BMI5": "BMI", "_AGEG5YR": "Age Group", "_INCOMG1": "Income", "_SEX": "Gender"}, inplace=True)

In [59]:
visualization_df.head()

Diabetes Status    Ethnicity    BMI        Age Group                 Income  \
0              No        White  14.54    Age 70 to 74    $25,000 to < $35,000   
2             Yes        Black  28.29    Age 70 to 74    $15,000 to < $25,000   
3             Yes        White  33.47    Age 60 to 64   $50,000 to < $100,000   
4             Yes  Multiracial  28.73     Age 75 to 79   $15,000 to < $25,000   
5              No        White  24.37  Age 80 or older   $35,000 to < $50,000   

   Gender  
0  Female  
2  Female  
3  Female  
4    Male  
5    Male

In [ ]:
# Write review_id_df to table in RDS
review_id_df.write.jdbc(url=jdbc_url, table='review_id_table', mode=mode, properties=config)

In [ ]:
# Write review_id_df to table in RDS
review_id_df.write.jdbc(url=jdbc_url, table='review_id_table', mode=mode, properties=config)

In [ ]:
# Configure settings for RDS
#from getpass import getpass
mode = "append"
jdbc_url="jdbc:postgresql://database-1.ch7jmx5vb0uq.us-east-2.rds.amazonaws.com:5432/database-1"
config = {"user":"postgres",
          "password": Quizab56(),
          "driver":"org.postgresql.Driver"}